language: python
sudo: required
python:
    - "3.9"

services:
    - docker

before_script: pip install docker-compose

script:
    - echo "Hi there, this is Mustafa here 2!"

deploy:
    provider: script
    script: bash travis.deploy.sh
    on:
        branch: master