version: "3.9"

services:
    app:
        build: .
        command: sh -c "python3 serve.py"
        # Replace username to your Docker Hub user
        image: ozdemirmustafa/cicd_pipeline:latest
        ports:
            - "80:8000"
        volumes:
            - ./src:/src